width: 5
height: 5
starts:
  - {x: 5}
exits:
  - {}
objects:
  - {type: wall, color: black}
  - {type: wall, color: black}
  - {type: wall, color: black}
  - {type: wall, color: black}
  - {type: food, color: orange}
